// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sftpconnection.proxies;

public enum AuthenticationType
{
	Username_and_password(new String[][] { new String[] { "en_US", "Username and password" } }),
	Username_and_connection_specific_private_key(new String[][] { new String[] { "en_US", "Username and connection specific private key" } }),
	Username_and_general_private_key(new String[][] { new String[] { "en_US", "Username and general private key" } });

	private java.util.Map<String,String> captions;

	private AuthenticationType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
