// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sftpconnection.proxies;

public class Session
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sessionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SFTPConnection.Session";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		User("User"),
		LastUsed("LastUsed"),
		Session_SFTPConfiguration("SFTPConnection.Session_SFTPConfiguration");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Session(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SFTPConnection.Session"));
	}

	protected Session(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sessionMendixObject)
	{
		if (sessionMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SFTPConnection.Session", sessionMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SFTPConnection.Session");

		this.sessionMendixObject = sessionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Session.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static sftpconnection.proxies.Session initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sftpconnection.proxies.Session.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static sftpconnection.proxies.Session initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sftpconnection.proxies.Session(context, mendixObject);
	}

	public static sftpconnection.proxies.Session load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sftpconnection.proxies.Session.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of User
	 */
	public final String getUser()
	{
		return getUser(getContext());
	}

	/**
	 * @param context
	 * @return value of User
	 */
	public final String getUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.User.toString());
	}

	/**
	 * Set value of User
	 * @param user
	 */
	public final void setUser(String user)
	{
		setUser(getContext(), user);
	}

	/**
	 * Set value of User
	 * @param context
	 * @param user
	 */
	public final void setUser(com.mendix.systemwideinterfaces.core.IContext context, String user)
	{
		getMendixObject().setValue(context, MemberNames.User.toString(), user);
	}

	/**
	 * @return value of LastUsed
	 */
	public final java.util.Date getLastUsed()
	{
		return getLastUsed(getContext());
	}

	/**
	 * @param context
	 * @return value of LastUsed
	 */
	public final java.util.Date getLastUsed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastUsed.toString());
	}

	/**
	 * Set value of LastUsed
	 * @param lastused
	 */
	public final void setLastUsed(java.util.Date lastused)
	{
		setLastUsed(getContext(), lastused);
	}

	/**
	 * Set value of LastUsed
	 * @param context
	 * @param lastused
	 */
	public final void setLastUsed(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastused)
	{
		getMendixObject().setValue(context, MemberNames.LastUsed.toString(), lastused);
	}

	/**
	 * @return value of Session_SFTPConfiguration
	 */
	public final sftpconnection.proxies.SFTPConfiguration getSession_SFTPConfiguration() throws com.mendix.core.CoreException
	{
		return getSession_SFTPConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of Session_SFTPConfiguration
	 */
	public final sftpconnection.proxies.SFTPConfiguration getSession_SFTPConfiguration(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		sftpconnection.proxies.SFTPConfiguration result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Session_SFTPConfiguration.toString());
		if (identifier != null)
			result = sftpconnection.proxies.SFTPConfiguration.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Session_SFTPConfiguration
	 * @param session_sftpconfiguration
	 */
	public final void setSession_SFTPConfiguration(sftpconnection.proxies.SFTPConfiguration session_sftpconfiguration)
	{
		setSession_SFTPConfiguration(getContext(), session_sftpconfiguration);
	}

	/**
	 * Set value of Session_SFTPConfiguration
	 * @param context
	 * @param session_sftpconfiguration
	 */
	public final void setSession_SFTPConfiguration(com.mendix.systemwideinterfaces.core.IContext context, sftpconnection.proxies.SFTPConfiguration session_sftpconfiguration)
	{
		if (session_sftpconfiguration == null)
			getMendixObject().setValue(context, MemberNames.Session_SFTPConfiguration.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Session_SFTPConfiguration.toString(), session_sftpconfiguration.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sessionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sftpconnection.proxies.Session that = (sftpconnection.proxies.Session) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SFTPConnection.Session";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
