// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package sftpconnection.proxies;

public class SFTPFileDocument
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sFTPFileDocumentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SFTPConnection.SFTPFileDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Directory("Directory"),
		Name("Name"),
		LastModificationDate("LastModificationDate");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SFTPFileDocument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "SFTPConnection.SFTPFileDocument"));
	}

	protected SFTPFileDocument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sFTPFileDocumentMendixObject)
	{
		if (sFTPFileDocumentMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("SFTPConnection.SFTPFileDocument", sFTPFileDocumentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a SFTPConnection.SFTPFileDocument");

		this.sFTPFileDocumentMendixObject = sFTPFileDocumentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SFTPFileDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static sftpconnection.proxies.SFTPFileDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return sftpconnection.proxies.SFTPFileDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static sftpconnection.proxies.SFTPFileDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new sftpconnection.proxies.SFTPFileDocument(context, mendixObject);
	}

	public static sftpconnection.proxies.SFTPFileDocument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return sftpconnection.proxies.SFTPFileDocument.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Directory
	 */
	public final String getDirectory()
	{
		return getDirectory(getContext());
	}

	/**
	 * @param context
	 * @return value of Directory
	 */
	public final String getDirectory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Directory.toString());
	}

	/**
	 * Set value of Directory
	 * @param directory
	 */
	public final void setDirectory(String directory)
	{
		setDirectory(getContext(), directory);
	}

	/**
	 * Set value of Directory
	 * @param context
	 * @param directory
	 */
	public final void setDirectory(com.mendix.systemwideinterfaces.core.IContext context, String directory)
	{
		getMendixObject().setValue(context, MemberNames.Directory.toString(), directory);
	}

	/**
	 * @return value of Name
	 */
	public final String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of LastModificationDate
	 */
	public final java.util.Date getLastModificationDate()
	{
		return getLastModificationDate(getContext());
	}

	/**
	 * @param context
	 * @return value of LastModificationDate
	 */
	public final java.util.Date getLastModificationDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastModificationDate.toString());
	}

	/**
	 * Set value of LastModificationDate
	 * @param lastmodificationdate
	 */
	public final void setLastModificationDate(java.util.Date lastmodificationdate)
	{
		setLastModificationDate(getContext(), lastmodificationdate);
	}

	/**
	 * Set value of LastModificationDate
	 * @param context
	 * @param lastmodificationdate
	 */
	public final void setLastModificationDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastmodificationdate)
	{
		getMendixObject().setValue(context, MemberNames.LastModificationDate.toString(), lastmodificationdate);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sFTPFileDocumentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final sftpconnection.proxies.SFTPFileDocument that = (sftpconnection.proxies.SFTPFileDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "SFTPConnection.SFTPFileDocument";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
