// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sftpconnection.actions;

import com.jcraft.jsch.Session;
import com.mendix.core.session.UserSession;
import sftpconnection.helpers.HandleFileSftp;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class DisconnectIdleSessions extends CustomJavaAction<Boolean>
{
	private String UserParameter1;

	public DisconnectIdleSessions(IContext context, String UserParameter1)
	{
		super(context);
		this.UserParameter1 = UserParameter1;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Session session = sftpconnection.helpers.HandleFileSftp.userSession.get(this.UserParameter1);
		session.disconnect();		
		
		return true;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "DisconnectIdleSessions";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
