// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sftpconnection.actions;

import java.util.ArrayList;
import sftpconnection.helpers.HandleFileSftp;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Get the list of file in the path of the server specified in the SFTPConfiguration. Only gets file, not directories.
 * 
 * Do not use this action directly, use SFTPConfiguration_GetDocumentList instead.
 */
public class GetFileListFromSFTPLocation extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __sftpConfiguration;
	private sftpconnection.proxies.SFTPConfiguration sftpConfiguration;

	public GetFileListFromSFTPLocation(IContext context, IMendixObject sftpConfiguration)
	{
		super(context);
		this.__sftpConfiguration = sftpConfiguration;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.sftpConfiguration = __sftpConfiguration == null ? null : sftpconnection.proxies.SFTPConfiguration.initialize(getContext(), __sftpConfiguration);

		// BEGIN USER CODE
		if (sftpConfiguration == null) {
			throw new IllegalArgumentException("The SFTPConfiguration is empty");
		}
		ArrayList<IMendixObject> SFTPFileDocumentList = HandleFileSftp.getFileListFromSFTP(sftpConfiguration, this.getContext());
		return SFTPFileDocumentList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "GetFileListFromSFTPLocation";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
