// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package sftpconnection.actions;

import sftpconnection.helpers.HandleFileSftp;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Connects to the specified server without validating the identity of the server. Gets the key and fingerprint of the server and saves them in the knownHosts object of the SFTPConfiguration,
 * 
 * Do not use this action directly, use IVK_SFTPConfiguration_SetKnownHosts instead.
 */
public class SetKnownHosts extends CustomJavaAction<Boolean>
{
	private IMendixObject __sftpConfiguration;
	private sftpconnection.proxies.SFTPConfiguration sftpConfiguration;

	public SetKnownHosts(IContext context, IMendixObject sftpConfiguration)
	{
		super(context);
		this.__sftpConfiguration = sftpConfiguration;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		this.sftpConfiguration = __sftpConfiguration == null ? null : sftpconnection.proxies.SFTPConfiguration.initialize(getContext(), __sftpConfiguration);

		// BEGIN USER CODE
		HandleFileSftp.setKnownHosts(sftpConfiguration, getContext());
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "SetKnownHosts";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
